from quantum_DP.action_space.locally_greedy import Locally_Greedy_ParamSpace
from quantum_DP.action_space.qubit_extremal import Qubit_Extremal_POVM_ParamSpace
from quantum_DP.action_space.qubit_projective import Qubit_Proj_ParamSpace
from quantum_DP.action_space.qutrit_projective import Qutrit_Proj_ParamSpace
